/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHomeRouteImport } from './routes/app-home'
import { Route as HeldOutEncodeRouteImport } from './routes/held-out-encode'
import { Route as LookalikeHonestyVerifyRouteImport } from './routes/lookalike-honesty-verify'
import { Route as ReEncodeRouteImport } from './routes/re-encode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/app-home',
  path: '/app-home',
  getParentRoute: () => rootRouteImport,
} as any)
const HeldOutEncodeRoute = HeldOutEncodeRouteImport.update({
  id: '/held-out-encode',
  path: '/held-out-encode',
  getParentRoute: () => rootRouteImport,
} as any)
const LookalikeHonestyVerifyRoute = LookalikeHonestyVerifyRouteImport.update({
  id: '/lookalike-honesty-verify',
  path: '/lookalike-honesty-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ReEncodeRoute = ReEncodeRouteImport.update({
  id: '/re-encode',
  path: '/re-encode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-home': typeof AppHomeRoute
  '/held-out-encode': typeof HeldOutEncodeRoute
  '/lookalike-honesty-verify': typeof LookalikeHonestyVerifyRoute
  '/re-encode': typeof ReEncodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-home': typeof AppHomeRoute
  '/held-out-encode': typeof HeldOutEncodeRoute
  '/lookalike-honesty-verify': typeof LookalikeHonestyVerifyRoute
  '/re-encode': typeof ReEncodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-home': typeof AppHomeRoute
  '/held-out-encode': typeof HeldOutEncodeRoute
  '/lookalike-honesty-verify': typeof LookalikeHonestyVerifyRoute
  '/re-encode': typeof ReEncodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app-home' | '/held-out-encode' | '/lookalike-honesty-verify' | '/re-encode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app-home' | '/held-out-encode' | '/lookalike-honesty-verify' | '/re-encode'
  id: '__root__' | '/' | '/app-home' | '/held-out-encode' | '/lookalike-honesty-verify' | '/re-encode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppHomeRoute: typeof AppHomeRoute
  HeldOutEncodeRoute: typeof HeldOutEncodeRoute
  LookalikeHonestyVerifyRoute: typeof LookalikeHonestyVerifyRoute
  ReEncodeRoute: typeof ReEncodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-home': {
      id: '/app-home'
      path: '/app-home'
      fullPath: '/app-home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/held-out-encode': {
      id: '/held-out-encode'
      path: '/held-out-encode'
      fullPath: '/held-out-encode'
      preLoaderRoute: typeof HeldOutEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookalike-honesty-verify': {
      id: '/lookalike-honesty-verify'
      path: '/lookalike-honesty-verify'
      fullPath: '/lookalike-honesty-verify'
      preLoaderRoute: typeof LookalikeHonestyVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/re-encode': {
      id: '/re-encode'
      path: '/re-encode'
      fullPath: '/re-encode'
      preLoaderRoute: typeof ReEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppHomeRoute: AppHomeRoute,
  HeldOutEncodeRoute: HeldOutEncodeRoute,
  LookalikeHonestyVerifyRoute: LookalikeHonestyVerifyRoute,
  ReEncodeRoute: ReEncodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
