/**
 * Lightweight metadata for the expanded FaceNet gallery.
 * IDs match public/celebs embeddings. Falls back to heuristics for unknown ids.
 */

export interface CatalogEntry {
  knownFor: string;
  tags: string[];
  accentHue: number;
}

const ACTOR = "Actor";
const ARTIST = "Artist";
const ATHLETE = "Athlete";
const PUBLIC = "Public figure";
const MODEL = "Model";

/** Hand-curated overrides for popular names. */
const CURATED: Record<string, CatalogEntry> = {
  "brad-pitt": { knownFor: ACTOR, tags: ["classic", "angular"], accentHue: 42 },
  "george-clooney": { knownFor: ACTOR, tags: ["classic", "silver"], accentHue: 210 },
  "denzel-washington": { knownFor: ACTOR, tags: ["intense", "classic"], accentHue: 28 },
  "idris-elba": { knownFor: ACTOR, tags: ["broad jaw"], accentHue: 18 },
  "ryan-gosling": { knownFor: ACTOR, tags: ["soft features"], accentHue: 200 },
  "timothee-chalamet": { knownFor: ACTOR, tags: ["angular", "youthful"], accentHue: 25 },
  "tom-holland": { knownFor: ACTOR, tags: ["boyish"], accentHue: 12 },
  "michael-b-jordan": { knownFor: ACTOR, tags: ["defined jaw"], accentHue: 8 },
  "chris-hemsworth": { knownFor: ACTOR, tags: ["square jaw"], accentHue: 38 },
  "keanu-reeves": { knownFor: ACTOR, tags: ["long face"], accentHue: 220 },
  "pedro-pascal": { knownFor: ACTOR, tags: ["warm eyes"], accentHue: 22 },
  "henry-cavill": { knownFor: ACTOR, tags: ["hero jaw"], accentHue: 205 },
  "zendaya": { knownFor: ACTOR, tags: ["high cheekbones"], accentHue: 340 },
  "scarlett-johansson": { knownFor: ACTOR, tags: ["full lips"], accentHue: 12 },
  "margot-robbie": { knownFor: ACTOR, tags: ["classic oval"], accentHue: 45 },
  "rihanna": { knownFor: ARTIST, tags: ["full features"], accentHue: 350 },
  "beyonce": { knownFor: ARTIST, tags: ["radiant"], accentHue: 45 },
  "the-weeknd": { knownFor: ARTIST, tags: ["angular"], accentHue: 0 },
  "dua-lipa": { knownFor: ARTIST, tags: ["cat eyes"], accentHue: 280 },
  "harry-styles": { knownFor: ARTIST, tags: ["soft features"], accentHue: 330 },
  "taylor-swift": { knownFor: ARTIST, tags: ["bright"], accentHue: 15 },
  "ariana-grande": { knownFor: ARTIST, tags: ["youthful"], accentHue: 320 },
  "billie-eilish": { knownFor: ARTIST, tags: ["soft features"], accentHue: 160 },
  "lady-gaga": { knownFor: ARTIST, tags: ["expressive"], accentHue: 300 },
  "adele": { knownFor: ARTIST, tags: ["classic"], accentHue: 25 },
  "selena-gomez": { knownFor: ARTIST, tags: ["bright eyes"], accentHue: 5 },
  "leonardo-dicaprio": { knownFor: ACTOR, tags: ["classic"], accentHue: 30 },
  "robert-downey-jr": { knownFor: ACTOR, tags: ["sharp"], accentHue: 20 },
  "tom-hanks": { knownFor: ACTOR, tags: ["warm"], accentHue: 40 },
  "will-smith": { knownFor: ACTOR, tags: ["bright smile"], accentHue: 15 },
  "dwayne-johnson": { knownFor: ACTOR, tags: ["broad"], accentHue: 25 },
  "ryan-reynolds": { knownFor: ACTOR, tags: ["sharp smile"], accentHue: 200 },
  "hugh-jackman": { knownFor: ACTOR, tags: ["strong jaw"], accentHue: 35 },
  "christian-bale": { knownFor: ACTOR, tags: ["angular"], accentHue: 10 },
  "cillian-murphy": { knownFor: ACTOR, tags: ["sharp eyes"], accentHue: 210 },
  "benedict-cumberbatch": { knownFor: ACTOR, tags: ["long face"], accentHue: 15 },
  "jason-momoa": { knownFor: ACTOR, tags: ["broad features"], accentHue: 18 },
  "tom-hardy": { knownFor: ACTOR, tags: ["rugged"], accentHue: 22 },
  "angelina-jolie": { knownFor: ACTOR, tags: ["full lips"], accentHue: 350 },
  "jennifer-aniston": { knownFor: ACTOR, tags: ["classic"], accentHue: 35 },
  "julia-roberts": { knownFor: ACTOR, tags: ["wide smile"], accentHue: 12 },
  "sandra-bullock": { knownFor: ACTOR, tags: ["warm"], accentHue: 25 },
  "meryl-streep": { knownFor: ACTOR, tags: ["expressive"], accentHue: 30 },
  "cate-blanchett": { knownFor: ACTOR, tags: ["sculpted"], accentHue: 200 },
  "nicole-kidman": { knownFor: ACTOR, tags: ["classic"], accentHue: 8 },
  "charlize-theron": { knownFor: ACTOR, tags: ["angular"], accentHue: 40 },
  "blake-lively": { knownFor: ACTOR, tags: ["bright"], accentHue: 20 },
  "emma-watson": { knownFor: ACTOR, tags: ["youthful"], accentHue: 210 },
  "natalie-portman": { knownFor: ACTOR, tags: ["fine features"], accentHue: 0 },
  "anya-taylor-joy": { knownFor: ACTOR, tags: ["wide eyes"], accentHue: 50 },
  "brie-larson": { knownFor: ACTOR, tags: ["bright"], accentHue: 15 },
  "kristen-stewart": { knownFor: ACTOR, tags: ["angular"], accentHue: 240 },
  "keira-knightley": { knownFor: ACTOR, tags: ["fine features"], accentHue: 30 },
  "halle-berry": { knownFor: ACTOR, tags: ["classic"], accentHue: 20 },
  "michelle-yeoh": { knownFor: ACTOR, tags: ["elegant"], accentHue: 5 },
  "gong-li": { knownFor: ACTOR, tags: ["sculpted"], accentHue: 0 },
  "shah-rukh-khan": { knownFor: ACTOR, tags: ["classic"], accentHue: 25 },
  "deepika-padukone": { knownFor: ACTOR, tags: ["striking eyes"], accentHue: 320 },
  "jackie-chan": { knownFor: ACTOR, tags: ["expressive"], accentHue: 15 },
  "rami-malek": { knownFor: ACTOR, tags: ["wide eyes"], accentHue: 200 },
  "paul-rudd": { knownFor: ACTOR, tags: ["boyish"], accentHue: 30 },
  "kevin-hart": { knownFor: ARTIST, tags: ["expressive"], accentHue: 18 },
  "adam-sandler": { knownFor: ACTOR, tags: ["warm"], accentHue: 40 },
  "johnny-depp": { knownFor: ACTOR, tags: ["angular"], accentHue: 25 },
  "kim-kardashian": { knownFor: PUBLIC, tags: ["defined"], accentHue: 10 },
  "lebron-james": { knownFor: ATHLETE, tags: ["powerful"], accentHue: 15 },
  "cristiano-ronaldo": { knownFor: ATHLETE, tags: ["sharp jaw"], accentHue: 200 },
  "lionel-messi": { knownFor: ATHLETE, tags: ["compact"], accentHue: 30 },
  "barack-obama": { knownFor: PUBLIC, tags: ["classic"], accentHue: 210 },
  "michelle-obama": { knownFor: PUBLIC, tags: ["warm"], accentHue: 25 },
  "elon-musk": { knownFor: PUBLIC, tags: ["soft features"], accentHue: 200 },
  "david-beckham": { knownFor: ATHLETE, tags: ["classic"], accentHue: 20 },
  "oprah-winfrey": { knownFor: PUBLIC, tags: ["radiant"], accentHue: 30 },
  "serena-williams": { knownFor: ATHLETE, tags: ["powerful"], accentHue: 18 },
  "iu": { knownFor: ARTIST, tags: ["fine features"], accentHue: 330 },
  "jennie-kim": { knownFor: ARTIST, tags: ["cat eyes"], accentHue: 0 },
  "drake": { knownFor: ARTIST, tags: ["soft features"], accentHue: 220 },
  "bruno-mars": { knownFor: ARTIST, tags: ["bright smile"], accentHue: 25 },
  "justin-bieber": { knownFor: ARTIST, tags: ["youthful"], accentHue: 40 },
  "ed-sheeran": { knownFor: ARTIST, tags: ["soft features"], accentHue: 15 },
  "matt-damon": { knownFor: ACTOR, tags: ["classic"], accentHue: 35 },
  "jake-gyllenhaal": { knownFor: ACTOR, tags: ["intense"], accentHue: 10 },
  "chris-pratt": { knownFor: ACTOR, tags: ["warm"], accentHue: 30 },
  "bradley-cooper": { knownFor: ACTOR, tags: ["angular"], accentHue: 200 },
  "joaquin-phoenix": { knownFor: ACTOR, tags: ["angular"], accentHue: 15 },
  "morgan-freeman": { knownFor: ACTOR, tags: ["classic"], accentHue: 25 },
  // Expanded International Curated Entries (Asia, Africa, Latin America, Europe, Middle East, North America, Oceania)
  "dev-patel": { knownFor: ACTOR, tags: ["intense", "defined jaw"], accentHue: 25 },
  "simu-liu": { knownFor: ACTOR, tags: ["sculpted", "athletic"], accentHue: 210 },
  "john-cho": { knownFor: ACTOR, tags: ["classic", "sharp"], accentHue: 195 },
  "donald-glover": { knownFor: ARTIST, tags: ["expressive", "creative"], accentHue: 35 },
  "mahershala-ali": { knownFor: ACTOR, tags: ["classic", "sculpted"], accentHue: 15 },
  "florence-pugh": { knownFor: ACTOR, tags: ["expressive", "defined"], accentHue: 40 },
  "ana-de-armas": { knownFor: ACTOR, tags: ["warm eyes", "soft features"], accentHue: 22 },
  "sydney-sweeney": { knownFor: ACTOR, tags: ["bright", "classic"], accentHue: 45 },
  "jennifer-lawrence": { knownFor: ACTOR, tags: ["expressive", "classic"], accentHue: 30 },
  "liu-yifei": { knownFor: ACTOR, tags: ["sculpted", "fine features"], accentHue: 340 },
  "gal-gadot": { knownFor: ACTOR, tags: ["striking", "classic"], accentHue: 200 },
  "zoe-kravitz": { knownFor: ACTOR, tags: ["sculpted", "fine features"], accentHue: 280 },
  "jenna-ortega": { knownFor: ACTOR, tags: ["expressive", "youthful"], accentHue: 260 },
  "ali-wong": { knownFor: ARTIST, tags: ["expressive", "bright"], accentHue: 330 },
  "elizabeth-olsen": { knownFor: ACTOR, tags: ["warm eyes", "expressive"], accentHue: 20 },
  "john-boyega": { knownFor: ACTOR, tags: ["broad jaw", "expressive"], accentHue: 12 },
  "millie-bobby-brown": { knownFor: ACTOR, tags: ["youthful", "bright"], accentHue: 310 },
  "andrew-garfield": { knownFor: ACTOR, tags: ["soft features", "expressive"], accentHue: 205 },
  "sandra-oh": { knownFor: ACTOR, tags: ["expressive", "classic"], accentHue: 320 },
  "oscar-isaac": { knownFor: ACTOR, tags: ["intense", "warm eyes"], accentHue: 18 },
  "adam-driver": { knownFor: ACTOR, tags: ["angular", "long face"], accentHue: 215 },
  "riz-ahmed": { knownFor: ACTOR, tags: ["intense", "expressive"], accentHue: 220 },
  "lupita-nyongo": { knownFor: ACTOR, tags: ["sculpted", "radiant"], accentHue: 345 },
  "awkwafina": { knownFor: ARTIST, tags: ["expressive", "bright"], accentHue: 35 },
  "priyanka-chopra": { knownFor: ACTOR, tags: ["striking", "full lips"], accentHue: 350 },
  "yara-shahidi": { knownFor: ACTOR, tags: ["radiant", "youthful"], accentHue: 25 },
  "uzo-aduba": { knownFor: ACTOR, tags: ["expressive", "radiant"], accentHue: 10 },
  "bad-bunny": { knownFor: ARTIST, tags: ["expressive", "bold"], accentHue: 270 },
  "daniel-kaluuya": { knownFor: ACTOR, tags: ["intense", "expressive"], accentHue: 15 },
  "chris-evans": { knownFor: ACTOR, tags: ["hero jaw", "classic"], accentHue: 210 },
  "tiffany-haddish": { knownFor: ACTOR, tags: ["bright smile", "expressive"], accentHue: 30 },
  "emma-stone": { knownFor: ACTOR, tags: ["expressive", "bright eyes"], accentHue: 12 },
  "viola-davis": { knownFor: ACTOR, tags: ["intense", "radiant"], accentHue: 340 },
  "salma-hayek": { knownFor: ACTOR, tags: ["striking", "classic"], accentHue: 5 },
  "jacob-elordi": { knownFor: ACTOR, tags: ["angular", "tall"], accentHue: 200 },
  "aaron-taylor-johnson": { knownFor: ACTOR, tags: ["sculpted", "intense"], accentHue: 215 },
  "adriana-lima": { knownFor: MODEL, tags: ["cat eyes", "striking"], accentHue: 330 },
  "aishwarya-rai": { knownFor: ACTOR, tags: ["striking eyes", "classic"], accentHue: 340 },
  "al-pacino": { knownFor: ACTOR, tags: ["intense", "classic"], accentHue: 25 },
  "alexander-skarsgard": { knownFor: ACTOR, tags: ["tall", "angular"], accentHue: 205 },
  "alia-bhatt": { knownFor: ACTOR, tags: ["youthful", "bright"], accentHue: 325 },
  "alicia-vikander": { knownFor: ACTOR, tags: ["fine features", "warm"], accentHue: 35 },
  "amy-adams": { knownFor: ACTOR, tags: ["warm eyes", "soft features"], accentHue: 15 },
  "andrew-scott": { knownFor: ACTOR, tags: ["expressive", "fine features"], accentHue: 190 },
  "angela-bassett": { knownFor: ACTOR, tags: ["sculpted", "commanding"], accentHue: 355 },
  "anna-sawai": { knownFor: ACTOR, tags: ["sculpted", "fine features"], accentHue: 220 },
  "ansel-elgort": { knownFor: ACTOR, tags: ["tall", "soft features"], accentHue: 200 },
  "anthony-hopkins": { knownFor: ACTOR, tags: ["classic", "intense"], accentHue: 40 },
  "anthony-mackie": { knownFor: ACTOR, tags: ["defined", "warm"], accentHue: 18 },
  "antonio-banderas": { knownFor: ACTOR, tags: ["classic", "warm eyes"], accentHue: 22 },
  "austin-butler": { knownFor: ACTOR, tags: ["sculpted", "angular"], accentHue: 42 },
  "bella-hadid": { knownFor: MODEL, tags: ["high cheekbones", "sculpted"], accentHue: 280 },
  "ben-affleck": { knownFor: ACTOR, tags: ["square jaw", "classic"], accentHue: 210 },
  "bill-gates": { knownFor: PUBLIC, tags: ["soft features", "classic"], accentHue: 200 },
  "bill-skarsgard": { knownFor: ACTOR, tags: ["angular", "intense"], accentHue: 260 },
  "britney-spears": { knownFor: ARTIST, tags: ["bright smile", "classic"], accentHue: 320 },
  "cara-delevingne": { knownFor: MODEL, tags: ["defined brows", "sculpted"], accentHue: 230 },
  "cardi-b": { knownFor: ARTIST, tags: ["expressive", "bold"], accentHue: 340 },
  "chadwick-boseman": { knownFor: ACTOR, tags: ["regal", "sculpted"], accentHue: 28 },
  "channing-tatum": { knownFor: ACTOR, tags: ["broad jaw", "athletic"], accentHue: 30 },
  "chloe-grace-moretz": { knownFor: ACTOR, tags: ["youthful", "expressive"], accentHue: 310 },
  "chris-pine": { knownFor: ACTOR, tags: ["classic", "bright eyes"], accentHue: 205 },
  "cole-sprouse": { knownFor: ACTOR, tags: ["soft features", "youthful"], accentHue: 220 },
  "colin-firth": { knownFor: ACTOR, tags: ["classic", "gentle"], accentHue: 215 },
  "dakota-johnson": { knownFor: ACTOR, tags: ["soft features", "classic"], accentHue: 10 },
  "daniel-craig": { knownFor: ACTOR, tags: ["sharp jaw", "intense"], accentHue: 200 },
  "diego-luna": { knownFor: ACTOR, tags: ["warm eyes", "expressive"], accentHue: 25 },
  "doja-cat": { knownFor: ARTIST, tags: ["expressive", "bold"], accentHue: 330 },
  "donnie-yen": { knownFor: ACTOR, tags: ["sculpted", "athletic"], accentHue: 15 },
  "drew-barrymore": { knownFor: ACTOR, tags: ["warm smile", "expressive"], accentHue: 35 },
  "eddie-redmayne": { knownFor: ACTOR, tags: ["fine features", "expressive"], accentHue: 40 },
  "elijah-wood": { knownFor: ACTOR, tags: ["wide eyes", "expressive"], accentHue: 200 },
  "emily-blunt": { knownFor: ACTOR, tags: ["classic", "bright eyes"], accentHue: 185 },
  "eva-longoria": { knownFor: ACTOR, tags: ["striking", "radiant"], accentHue: 10 },
  "fan-bingbing": { knownFor: ACTOR, tags: ["striking", "fine features"], accentHue: 345 },
  "gael-garcia-bernal": { knownFor: ACTOR, tags: ["expressive", "warm eyes"], accentHue: 20 },
  "gary-oldman": { knownFor: ACTOR, tags: ["expressive", "classic"], accentHue: 210 },
  "gemma-chan": { knownFor: ACTOR, tags: ["sculpted", "classic"], accentHue: 270 },
  "gigi-hadid": { knownFor: MODEL, tags: ["soft features", "radiant"], accentHue: 40 },
  "glen-powell": { knownFor: ACTOR, tags: ["square jaw", "bright smile"], accentHue: 30 },
  "gong-yoo": { knownFor: ACTOR, tags: ["tall", "classic"], accentHue: 205 },
  "gwyneth-paltrow": { knownFor: ACTOR, tags: ["classic", "fine features"], accentHue: 45 },
  "hailee-steinfeld": { knownFor: ACTOR, tags: ["bright", "expressive"], accentHue: 325 },
  "heidi-klum": { knownFor: MODEL, tags: ["bright smile", "sculpted"], accentHue: 40 },
  "helen-mirren": { knownFor: ACTOR, tags: ["regal", "classic"], accentHue: 210 },
  "helena-bonham-carter": { knownFor: ACTOR, tags: ["expressive", "classic"], accentHue: 280 },
  "henry-golding": { knownFor: ACTOR, tags: ["classic", "warm smile"], accentHue: 25 },
  "hrithik-roshan": { knownFor: ACTOR, tags: ["sculpted", "striking eyes"], accentHue: 195 },
  "hugh-grant": { knownFor: ACTOR, tags: ["classic", "expressive"], accentHue: 215 },
  "hunter-schafer": { knownFor: MODEL, tags: ["sculpted", "fine features"], accentHue: 290 },
  "hyun-bin": { knownFor: ACTOR, tags: ["sculpted", "classic"], accentHue: 210 },
  "ian-somerhalder": { knownFor: ACTOR, tags: ["sharp jaw", "striking eyes"], accentHue: 200 },
  "jamie-dornan": { knownFor: ACTOR, tags: ["defined jaw", "rugged"], accentHue: 15 },
  "javier-bardem": { knownFor: ACTOR, tags: ["intense", "rugged"], accentHue: 10 },
  "jeff-bezos": { knownFor: PUBLIC, tags: ["defined", "classic"], accentHue: 190 },
  "jennifer-lopez": { knownFor: ARTIST, tags: ["radiant", "sculpted"], accentHue: 30 },
  "jessica-alba": { knownFor: ACTOR, tags: ["radiant", "classic"], accentHue: 25 },
  "jessica-chastain": { knownFor: ACTOR, tags: ["striking", "warm eyes"], accentHue: 15 },
  "jet-li": { knownFor: ACTOR, tags: ["athletic", "expressive"], accentHue: 20 },
  "jisoo": { knownFor: ARTIST, tags: ["fine features", "radiant"], accentHue: 335 },
  "john-krasinski": { knownFor: ACTOR, tags: ["expressive", "warm"], accentHue: 205 },
  "jonah-hill": { knownFor: ACTOR, tags: ["expressive", "soft features"], accentHue: 35 },
  "jonathan-bailey": { knownFor: ACTOR, tags: ["classic", "expressive"], accentHue: 210 },
  "joseph-gordon-levitt": { knownFor: ACTOR, tags: ["boyish", "expressive"], accentHue: 195 },
  "josh-hutcherson": { knownFor: ACTOR, tags: ["square jaw", "warm eyes"], accentHue: 25 },
  "kate-middleton": { knownFor: PUBLIC, tags: ["regal", "classic"], accentHue: 215 },
  "kate-winslet": { knownFor: ACTOR, tags: ["classic", "expressive"], accentHue: 30 },
  "ken-watanabe": { knownFor: ACTOR, tags: ["commanding", "classic"], accentHue: 15 },
  "kendall-jenner": { knownFor: MODEL, tags: ["high cheekbones", "defined"], accentHue: 350 },
  "kendrick-lamar": { knownFor: ARTIST, tags: ["focused", "expressive"], accentHue: 18 },
  "kerry-washington": { knownFor: ACTOR, tags: ["expressive", "radiant"], accentHue: 340 },
  "kit-harington": { knownFor: ACTOR, tags: ["intense", "defined jaw"], accentHue: 220 },
  "kylian-mbappe": { knownFor: ATHLETE, tags: ["athletic", "radiant"], accentHue: 210 },
  "kylie-jenner": { knownFor: MODEL, tags: ["full lips", "defined"], accentHue: 330 },
  "lana-condor": { knownFor: ACTOR, tags: ["youthful", "bright"], accentHue: 320 },
  "laurence-fishburne": { knownFor: ACTOR, tags: ["commanding", "classic"], accentHue: 10 },
  "lee-jung-jae": { knownFor: ACTOR, tags: ["classic", "expressive"], accentHue: 200 },
  "lee-min-ho": { knownFor: ACTOR, tags: ["sculpted", "tall"], accentHue: 215 },
  "liam-hemsworth": { knownFor: ACTOR, tags: ["square jaw", "athletic"], accentHue: 35 },
};

const ATHLETE_HINTS = [
  "james", "curry", "durant", "williams", "biles", "osaka", "federer", "nadal",
  "djokovic", "ronaldo", "messi", "neymar", "mbappe", "beckham",
];
const ARTIST_HINTS = [
  "swift", "grande", "eilish", "rodrigo", "gaga", "adele", "beyonce", "rihanna",
  "cardi", "stallion", "doja", "minaj", "sza", "lizzo", "cyrus", "perry",
  "spears", "lopez", "shakira", "drake", "lamar", "malone", "mars", "bieber",
  "sheeran", "mendes", "malik", "styles", "weeknd", "bunny", "lipa", "jennie",
  "jisoo", "rose", "lisa", "iu",
];
const MODEL_HINTS = [
  "hadid", "jenner", "kardashian", "delevingne", "ratajkowski", "lima",
  "bundchen", "crawford", "campbell", "banks", "klum",
];
const PUBLIC_HINTS = [
  "obama", "harris", "musk", "zuckerberg", "bezos", "cook", "gates",
  "prince", "meghan", "kate", "middleton", "oprah", "fallon", "colbert",
  "noah", "letterman",
];

function hashHue(id: string): number {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) >>> 0;
  return h % 360;
}

export function catalogFor(id: string): CatalogEntry {
  if (CURATED[id]) return CURATED[id]!;
  const lower = id.toLowerCase();
  let knownFor = ACTOR;
  const tags: string[] = [];
  if (ATHLETE_HINTS.some((h) => lower.includes(h))) knownFor = ATHLETE;
  else if (MODEL_HINTS.some((h) => lower.includes(h))) knownFor = MODEL;
  else if (PUBLIC_HINTS.some((h) => lower.includes(h))) knownFor = PUBLIC;
  else if (ARTIST_HINTS.some((h) => lower.includes(h))) knownFor = ARTIST;
  return { knownFor, tags, accentHue: hashHue(id) };
}
